export const data = {
  technologyAdoption: {
    booleanValues: ['Yes', 'No', 'May be'],
    technologyOpinions: [
      {
        formCntrlName: 'tissueCulture',
        title: 'Tissue culture / Hybrid seeds',
      },
      { formCntrlName: 'polyHouse', title: 'Poly house' },
      { formCntrlName: 'microIrrigation', title: 'Micro irrigation' },
      {
        formCntrlName: 'iotSensors',
        title: 'IoT sensors which help to track farm requirements of nutrition',
      },
      {
        formCntrlName: 'weatherData',
        title:
          'Weather data to help plan in advance for taking preventive measures on farm',
      },
      {
        formCntrlName: 'satelliteTracking',
        title: 'Satellite based tracking of crop health',
      },
    ],
  },

  produceAggregator: {
    verticals: [
      'Working capital cycle requirement',
      'Crop advisory on taking high quality yield',
      'Access to good quality Agri inputs',
      'Market linkage with produce aggregation',
      'Food Processing and Branding',
      'Warehousing',
    ],
    associatedWithFPO: [
      'On demand access to financing',
      'On demand access to fertilizer',
      'On demand access to pesticide',
      'On demand access to seeds',
      'Convenience to sale of produce',
      'Reducing number of middlemen while selling produce',
      'Marketing / Branding of produce',
      'Lower price of Inputs and Raw materials incl. fertilizer, pesticide, seeds etc.',
      'Transporting produce',
      'Receiving money at farm gate only without worrying on sale',
      'Access to technology and Cultivation advisory',
      'Social factors: Caste, Creed, Colour, Religion',
    ],
    enrolFPO: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    followSuggestions: ['Yes', 'No', 'May be'],
    consolidateLoans: ['Yes', 'No', 'May be'],
  },
  cropMarket: {
    seedProcure: [
      'Locally from village',
      'Hybrid variety seeds from input supplier',
      'FPO seed outlet',
      'KVK',
      'Last year produce',
    ],
    varietyComparison: [
      'High Yield',
      'No change in Yield',
      'Disease resistant',
      'Stress Tolerant',
      'Less Irrigation',
    ],
    fertilizerPurchase: ['Village Shop', 'Local Mandi', 'Government outlet'],
    pesticideQuality: [
      'Very satisfied',
      'Quite satisfied',
      'Not so satisfied',
      'Very dissatisfied',
    ],
    fertilizerAdvise: [
      'Self-advised',
      'advised by fertilizer shop owner',
      'advised by KVK',
    ],
    farmGateGrading: ['Yes', 'No'],
    durationReceivingMoney: [
      'On the spot at farm gate',
      'Less than 7 days',
      '10 to 15 days',
      '15 to 30 days',
    ],
    warehouseProduce: ['Yes', 'No'],
  },
  demoGraphic: {
    gender: ['Male', 'Female', 'Other'],
    religion: [
      'Hindu',
      'Muslim',
      'Sikh',
      'Christian',
      'Zoroastrian',
      'Buddhist',
      'Others',
    ],
    caste: ['SC', 'ST', 'OBC', 'General', 'Others'],
    relation: [
      'Father',
      'Mother',
      'Sister',
      'Brother',
      'Son',
      'Daughter',
      'Husband',
      'Wife',
      'Other',
    ],
    education: ['No Education', '10th', 'PUC', 'Graduate', 'PhD'],
    occupation: [
      'Farmer',
      'House Wife',
      'Student',
      'Self Employed',
      'Professional',
    ],
    propertyStatus: ['Own', 'Parental', 'Rented', 'Leased', 'Company Provided'],
    commOrPerAddress: ['Same as above', 'Different address'],
    dependency: [1, 2],
    innovativeWaysFarming: [
      'Mulch',
      'Solar Pump',
      'Water Soluble Fertilizers',
      'IoT/Drone',
      'Weather Updates',
      'SOPs',
    ],
    agriculturalInterest: [
      'Very much Interested',
      'Interested',
      'May be',
      'Not Interested',
    ],
    sourceOfIncome: [
      'Shop',
      'Govt. Service',
      'Private Service/Self employed',
      'Renting Heavy farm machinery or equipment',
      'Dairy Income machinery or equipment',
    ],
    phoneType: ['Feature Phone', 'Smart Phone', 'No Personal Phone'],
    phoneOperating: ['I Check Mostly', 'Somebody Else', 'Shared Phone'],
    adviceMedium: ['SMS', 'Whatsapp', 'Telephone Call', 'Physical Visits'],
    cultivationAdvice: [
      'Neighbouring farmer/family',
      'Company Doctor',
      'TV Program',
      'KVK',
      'Youtube',
      'Facebook',
    ],
    propertyType: ['House', 'Land', 'Shop'],
    ownerShipType: [
      'Leased (Joint/Self)',
      'Owned (Joint/Self)',
      'Share Cropping',
    ],
    particular: ['NA'],
  },
  financialPlan: {
    cropLoanProduct: ['Crop-Loan Product 1'],
    KCCLoanBank: [
      'SBI',
      'BoB',
      'PNB',
      'RRB',
      'NABARD',
      'ICICI',
      'HDFC',
      'Axis',
    ],
    farmMachinery: [
      'Tiller',
      'Seed drill',
      'Spraying machine',
      'Rotavator',
      'Combine Harvester',
      'Reaper',
      'Tillage Implements',
      'Thresher',
    ],
    pledgedCollateral: [
      'Output is sold to the credit supplier',
      'Agricultural Land',
    ],
    reasonAgent: [
      'Working Capital cycle requirement',
      'Capital',
      'Finance for inputs',
      'Rollover of credit',
      'Produce buyback guarantee/obligation',
      'Interest rate',
      'Repayment period',
    ],
    insuranceType: [
      'Multiple Peril Crop Insurance (MPCI)',
      'Crop-Hail Insurance',
      'Animal Agricultural Insurance',
      'Crop Agricultural Insurance',
      'Farm Property and Equipment Agricultural Insurance',
      'LIC',
      'Education',
      'Medical',
    ],
    cropSoldPlace: [
      'Local Mandi',
      'District Mandi',
      'Farm gate aggregator',
      'Arhatiya',
    ],
  },
  commonData: {
    crops: [
      'Mustard',
      'Cumin',
      'Gram',
      'Isabgol',
      'Cotton',
      'Wheat',
      'Barley',
      'Peas',
      'Rice',
      'Maize',
      'Jowar',
      'Bajra',
      'Tur',
      'Moong',
      'Urad',
      'Jute',
      'Groundnut',
      'Soybean',
      'Seasonal Fruits',
      'Vegetables',
      'Fodder Crops',
    ],
    season: [
      'Rabi 2022',
      'Kharif 2022',
      'Rabi 2021',
      'Kharif 2021',
      'Rabi 2020',
      'Kharif 2020',
      'Rabi 2019',
      'Kharif 2019',
    ],
  },
  fieldInfo: {
    irrigationSystem: ['Surface Irrigation'],
    waterSource: ['Pond', 'Well', 'Canal'],
    ownerShipType: [
      'Leased (Joint/Self)',
      'Owned (Joint/Self)',
      'Share Cropping',
    ],
    cropCycleOnReports: ['Yes', 'No', 'May be'],
    soilQuality: ['Poor', 'Fair', 'Good'],
    yesNo: ['Yes', 'No'],
    typeOfTest: ['Soil', 'Water'],
  },
  coApplicant: [],
};
